---
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

driver:
  name: vagrant

platforms:
  - name: centos-6.4
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[etcd::compile_time]
      - recipe[ktc-utils]
      - recipe[utils_test::helpers]
    attributes:
      authorization:
        sudo:
          users:
            - 'vagrant'
      etcd:
        args: '-c 127.0.0.1:4001 -s 127.0.0.1:7001 -f'
        servers:
          - 127.0.0.1
      ha_disabled: true
