AllCops:
  Includes:
    - metadata.rb
    - Gemfile
    - attributes/**
    - recipes/**
    - libraries/**
    - providers/**
    - resources/**
  Excludes:
    - spec/**
    - test/**
    - vendor/**

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile
